<?php
return [
    'RINGCENTRAL_CLIENTID'=>env('RINGCENTRAL_CLIENTID',''),
    'RINGCENTRAL_CLIENTSECRET'=>env('RINGCENTRAL_CLIENTSECRET',''),
    'RINGCENTRAL_SERVER'=>env('RINGCENTRAL_SERVER','https://platform.devtest.ringcentral.com'),
    'RINGCENTRAL_USERNAME'=>env('RINGCENTRAL_USERNAME',''),
    'RINGCENTRAL_PASSWORD'=>env('RINGCENTRAL_PASSWORD',''),
    'RINGCENTRAL_EXTENSION'=>env('RINGCENTRAL_EXTENSION','')
];
